### ISSUE TITLE
dropping mosaic frame

### ISSUE THREAD

**Issue by atiti** [Freescale/libimxvpuapi#1]
Hi there,

Love the library, so much cleaner and understandable!
I'm trying to decode an intra-refreshed h264 stream (with only P-frames), and the decoder is returning "trace: dropping mosaic frame" for each frame.

Do you have any ideas on what could be the cause?

Cheers,
Attila

**Comment by dv1** [comment]
This project unfortunately got delayed a lot. I can finally continue, and just pushed the first working version of the vpulib backend. Note that the encoder is not implemented yet there.

I never did anything with the V4L output, but recommend to use G2D instead of IPU for displaying frames. IPU is very picky with regards to the input parameters, and requires tiling sometimes. G2D is much more generic. It supports less formats, but this is mostly irrelevant for video playback, since the VPU outputs I420 data for all bitstream formats (except in some cases with MJPEG data).

**Comment by atiti** [comment]
Looks awesome! Will play around with it. :-) 

Since the last post we've implemented GLES for display, so we can also use the GPU for post processing.
