### ISSUE TITLE
MJPG encode

### ISSUE THREAD

**Issue by Malek44** [Freescale/libimxvpuapi#2]
Hi,

I am trying to use this library to encode a (4416 x 3312) image to JPEG using MJPG encoder.
I used your example given for H.264 and I changed the format to MJPG.
It compiles OK, but when I ran it I got an error saying: "invalid codec format"

By looking at the code, I found out that the library only support MPEG4, H263 and H264 formats for encoding (according to switch statement in  libimxvpuapi/imxvpuapi_fslwrapper.c line 1407).

Can you point me on how I can add MJPG encoding to the library?

Thanks,
Malek

**Comment by dv1** [comment]
Sorry for the late reply :/ I couldn't do anything with imxvpuapi over the last few months, unfortunately. Hopefully this will change soon (I'll need the library in another project).

Encoding is not planned yet, although the API for it is defined. It should be much easier to implement encoding compared to decoding in the imxvpuapi_fslwrapper.c file, since the encoder does not support frame reordering. gstreamer-imx contains encoders based on the FSL wrapper. I would use their code as a starting point (in fact, this is what I originally had in mind).

Encoder support in imxvpuapi_vpulib.c is another matter. I have other plans for that one first.

**Comment by dv1** [comment]
MJPEG encoding is in place now. Development has been going on for a while as part of another project (gstreamer-imx), but I finally had the time to port it back.
