### ISSUE TITLE
Top portion of frame distorted

### ISSUE THREAD

**Issue by mikeDonahoe** [Freescale/libimxvpuapi#41]
Working on Accelerated playback in Chromium on the iMX6 and I'm noticing a strange issue (see video).  Looks to only appear on videos that are in Portrait mode.  Initially, I had been using v1 of the API and never observed this issue.

https://youtu.be/DF8BmeSCNGw

One thing I noticed is the actual_frame_width/height always seems to match aligned_frame_width/height.

[6031:6048:0814/200253.282748:VERBOSE1:imxvpu_video_decode_accelerator.cc(480)] Associating picture buffer 0/17 ID 0 with framebuffer #0 virtual address 0x52d09000 physical address 0x76480000 actual width 640 actual height 368 aligned width 640 aligned height 368 texture id 23
[6031:6048:0814/200253.282843:VERBOSE1:imxvpu_video_decode_accelerator.cc(1021)] Adding output buffer 0 to queue

Video that glitches
[6314:6332:0814/200550.319460:VERBOSE1:imxvpu_video_decode_accelerator.cc(480)] Associating picture buffer 2/17 ID 2 with framebuffer #2 virtual address 0x57003000 physical address 0x76300000 actual width 368 actual height 368 aligned width 368 aligned height 368 texture id 25

I ended up adding code that dumps the raw frame right after a IMX_VPU_API_DEC_OUTPUT_CODE_DECODED_FRAME_AVAILABLE and I see that the image is corrupted.

![image](https://user-images.githubusercontent.com/6437324/90295803-88f8a280-de4f-11ea-9a5f-79299b1994f9.png)

![image](https://user-images.githubusercontent.com/6437324/90295864-a88fcb00-de4f-11ea-843d-4647f76ac131.png)

-Thanks

**Comment by mikeDonahoe** [comment]
For clarity, the actual frames are NV12.  I inadvertently selected NV21 on rawpixels.

**Comment by dv1** [comment]
For a long time I had no clue what could cause this. But lately I've seen something similar show up on another project that patched Chromium. It turns out to be a fencing issue: The VPU decodes into contiguous memory blocks that are still being read by the GPU because the media stack returned that memory block to the VPU too early. This is effectively a race condition, just in the GPU-VPU pair. The solution was to activate GPU fences to make sure the memory block is only returned when the GPU is really truly done drawing the frame. This is accomplished by enabling the read_lock_fences_enabled flag in the video frame metadata: https://chromium.googlesource.com/chromium/src/media/+/refs/heads/main/base/video_frame_metadata.h#110

If you use Picture instances, these have that flag as well: https://chromium.googlesource.com/chromium/src/media/+/refs/heads/main/video/picture.h#139

**Comment by mikeDonahoe** [comment]
Testing without Chromium produced the same results.  I simply was taking the decoded frames directly to a file.  See the previous post where I explain even using the provided decode-example resulted in corrupt frames.
