### ISSUE TITLE
h264 encoding video distortion 

### ISSUE THREAD

**Issue by Donnyp751** [Freescale/libimxvpuapi#56]
It seems that a green visual effect starts from the top every second, and gets a little worse with each frame until the frame is refreshed. At the default gop-size of 16 it's flashing at approx 1.5-2 hz, on just the top 50 pixels. But if you increase the gop-size to like 100 or so you can see the green spread further down the image over a few seconds before getting the new frame and resetting to a clean image.
screenshot from the start, and another towards the end of a cycle.

![Screenshot from 2023-02-06 08-34-05](https://user-images.githubusercontent.com/16264172/218830316-2ba38cc4-cc56-4a89-b905-210f51f56d7d.png)

The visual distortion can be seen at the top left of the image.

![Screenshot from 2023-02-06 08-34-32](https://user-images.githubusercontent.com/16264172/218830320-9b01cd48-12cc-4c2b-9981-75a3e5ef106e.png)

It seems to be a recent issue, I didn't see this prior to changing the aligned_frame_height for the imx6 vpu encoding issues I was experiencing before, but the previous issue could have been masking this one.

**Comment by Donnyp751** [comment]
Reducing the GOP-size to 1,2 it gets rid of the visual effects, but also increases the bitrate/decreases quality to bitrate ratio

**Comment by Donnyp751** [comment]
@dv1 Have you seen anything like this on your IMX6 test system or have any recommendation's for mitigating?

**Comment by bschuste** [comment]
Hi,
I am seeing the same type of issue. Which kernel version are you using?

**Comment by bschuste** [comment]
Thank you for the info, I am using 5.15, the ipu3 and vpu drivers have very few changes between kernel versions so it is probably not a kernel version issue. Most probably libimxvpuapi2 has still some bug.

**Comment by bschuste** [comment]
I notice that it appears when the height is not a multiple of 16. Are you experiencing the same?

**Comment by dv1** [comment]
@bschuste @Donnyp751  Have you tried again with latest git master? There are a number of alignment related fixes included.

**Comment by Donnyp751** [comment]
Yes, still is occurring. It seems to get worse each frame until a new I frame is received then it resets to a good image for a frame before getting worse again.

**Comment by Donnyp751** [comment]
Here is with the latest master b79a50a
https://drive.google.com/file/d/17B-erfoMxoZRvGsAv_Tc8COcQWBXIqZr/view?usp=share_link

**Comment by bschuste** [comment]
Indeed, it still occurs. This particular visual defect appeared with commit e5c16b93a0695f2f76d85514f138ef49a323d5a2 as the alignment of the frame height changed from 16 to 2. This commit seems to try to fix a different visual effect that shows a greenish bar at the bottom of the frame. The luminance is correct but not the chrominance.
In the previous version (0.10.3), the frame height was aligned to 16, see line 634 of file imxvpuapi_vpulib.c

This gstreamer command line example shows the issue:
```
gst-launch-1.0 videotestsrc pattern=15 num-buffers=120 ! \
video/x-raw, format="I420", width=640, height=360, framerate=30/1 ! \
imxvpuenc_h264 bitrate=750 gop-size=60 ! \
h264parse ! \
rtph264pay config-interval=1 ! \
rtph264depay ! \
h264parse ! \
imxvpudec_h264 ! \
queue ! \
glimagesink
```

**Comment by Donnyp751** [comment]
Just wanted to follow up as this is still an issue. Anyone found a fix or mitigation?

**Comment by dv1** [comment]
@bschuste Interesting - if I use `waylandsink` instead of `glimagesink`, I don't see the error. Perhaps something is wrong with the video meta. I'll check.

**Comment by dv1** [comment]
@Donnyp751 @bschuste I think I found out why this is happening when using `glimagesink`. GstGL's uploader mechanism supports Vivante direct textures. They however cannot handle plane offsets directly. Consequently, when there are padding rows between planes (which is true in the cases with the green bars), the uploader does not skip the padding rows, and instead shows them on screen. This is also why `waylandsink` and `imxg2dvideosink` are not affected - they can handle plane offsets directly.

I wrote a commit to add a fallback mechanism to the Vivante direct texture GL uploader that adjusts UV coordinates in the GLSL shaders to exclude the padding rows. [The commit is here, in my branch.](https://gitlab.freedesktop.org/dv1/gstreamer/-/commit/cb8ceb5b9ea8e1e8e78a63871234a33131c475f1) This is still a draft - it is not ready for inclusion into GstGL. One alternative would be to use the DirectDmabuf uploader inside GstGL. That one can handle plane offsets, but in my tests, it was less efficient.

I'll revisit this commit of mine in GStreamer upstream as part of a new merge request. Either way, if you can re-test your pipelines with `waylandsink` and `imxg2dvideosink`, and see if the green bars are gone, it would help. Alternatively, apply the linked commit to gst-plugins-base, and the bars should be gone even when using `glimagesink`. (Note that you need to patch with the `-p3` argument due to the `subprojects/gst-plugins-base/` subdirectory in the git repository.)

**Comment by dv1** [comment]
@Donnyp751 Can you post and example gst-launch line? And what is the resolution?

**Comment by Donnyp751** [comment]
Here are pipelines I have tested with before that have the video issues.

gst-launch-1.0 -v  imxv4l2videosrc ! videoconvert ! video/x-raw,
format=NV12,framerate=30/1  ! imxipuvideotransform  ! video/x-raw,width=1920,hei
ght=1080, format=NV12  ! imxvpuenc_h264 bitrate=5000 ! rtph264pay ! udpsink host
=192.168.210.26 port=5004 sync=false

gst-launch-1.0 -v  imxv4l2videosrc ! videoconvert ! video/x-raw,format=I4
20,framerate=30/1  ! imxvpuenc_h264 bitrate=5000 ! rtph264pay ! udpsink host=192.168.210.26 port=5004 sync=f
alse

I can get a device to setup to test with the new library again. I will get back to you shortly about that.

**Comment by Donnyp751** [comment]
@dv1 So testing with bitrate = 0, and quantization = 10 the visual issues do not appear. The pipeline is very unstable however, jumping between 1 and 9 FPS, averaging around 5 FPS

**Comment by dv1** [comment]
This is probably because the frames are very large. Try quantization 17.

**Comment by Donnyp751** [comment]
17 -> 6 FPS avg
20 -> 7.5 FPS avg
25 -> 28 FPS avg (but blue/neon green visual effects started to appear at the top)
30 -> 30 FPS avg (but worse blue/neon green visual effects)

**Comment by dv1** [comment]
I suggest this pipeline instead:

`gst-launch-1.0 -v imxv4l2videosrc ! queue ! video/x-raw,width=1920,height=1080,format=NV12,framerate=30/1 ! imxipuvideotransform ! imxvpuenc_h264 quantization=17 ! rtph264pay ! queue ! udpsink host=192.168.210.26 port=5004 sync=false

**Comment by Donnyp751** [comment]
So with that pipeline I get 23 FPS avg, and the video quality is good without any visual issues. Running at 90% CPU usage however. 

Is this a sign that the issue is what you suspect in the GL uploader?

**Comment by dv1** [comment]
I think we are seeing a couple of different issues.

First, the visual artifacts you saw are caused by the encoder itself. Somehow, encoding of the P-frames seems to allocate the quantization unevenly across the frame. As soon as an I-frame is produced, the artifacts go away again. When you look at the line above, you can observe some sort of cyclic behavior. With higher bitrates or higher quantization values, this does not happen, since there is a large amount of room for the encoded data, so the overall quantization is low. But this seems like a bug to me, especially since this did not happen with libimxvpuapi v1. I'll investigate the VPU's behavior.

The second issue is what @bschuste reported. That one is caused by the DirectVIV uploader.

The third issue we see in your case is the CPU usage. That one is caused by `rtph264pay`. With low quantization or high bitrate values, `imxvpuenc_h264` produces large encoded buffers. For example, with bitrate 5000, I get output gstbuffer sizes like 24000 bytes. With bitrate 0 and quantization 10, the sizes are rather around 207000 bytes. `rtph264pay` has to split these buffers into smaller buffers that fit within the UDP's MTU size, which is 1400 bytes. Out of one 207000-bytes gstbuffer, `rtph264pay` has to produce 207000/1400 ~ 147 MTU-sized buffers. This drives up CPU usage. However, I don't get 90%, but this may be because of CPU frequency and/or RAM bandwidth differences.

**Comment by Donnyp751** [comment]
That makes sense, when I made the dropped the GOP size to 1 the issue went away, as well as you could see the cyclic behavior changing with the GOP size. 

Is this issue reproduceable on your test system?

**Comment by dv1** [comment]
It is, and it is much more apparent with this pipeline:

    gst-launch-1.0 videotestsrc ! video/x-raw,width=640,height=360 ! imxvpuenc_h264 bitrate=128 ! h264parse ! queue ! imxvpudec_h264 ! queue ! imxg2dvideosink

**Comment by dv1** [comment]
Update: It seems to happen if the height is not an integer multiple of 16. Try for example this pipeline by comparison:

    gst-launch-1.0 videotestsrc ! video/x-raw,width=640,height=368 ! imxvpuenc_h264 bitrate=128 ! h264parse ! queue ! imxvpudec_h264 ! queue ! imxg2dvideosink

Note that 360 is not an integer multiple of 16, but 368 is.

In your case, try using 1280x720 instead of 1920x1080. 720 is an integer multiple of 16, while 1080 isn't. This is not meant to be the final fix, just a test. With 1280x720, your issue should not appear, even with a very low bitrate.

**Comment by Donnyp751** [comment]
Yes, that is the case for sure. I could run the video at 1920x1024 just fine.

**Comment by dv1** [comment]
@Donnyp751 Good news, I think I found a fix. Try latest git master.

**Comment by Donnyp751** [comment]
That resolves it, I am running your latest release right now for testing.
